/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Usos.Leer;
import java.net.URL;
import java.util.Set;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class Eleccion_NO extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Eleccion_NO() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelLogo1 = new javax.swing.JLabel();
        jBotonClientes = new javax.swing.JButton();
        jBotonVentas = new javax.swing.JButton();
        jBotonProduccion = new javax.swing.JButton();
        jBackground = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 150, 136));

        jPanel1.setBackground(new java.awt.Color(0, 96, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoGestiCor.png"))); // NOI18N
        jPanel1.add(jLabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -120, 280, 180));

        jBotonClientes.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jBotonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N
        jBotonClientes.setText("         Gestion Clientes");
        jBotonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 310, -1));

        jBotonVentas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jBotonVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ventas.png"))); // NOI18N
        jBotonVentas.setText("         Gestion de Ventas");
        jBotonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonVentasActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 310, -1));

        jBotonProduccion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jBotonProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/produccion.png"))); // NOI18N
        jBotonProduccion.setText("         Gestion de Produccion");
        jBotonProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonProduccionActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 310, -1));

        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gradient_800_600.png"))); // NOI18N
        jPanel1.add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonProduccionActionPerformed
        // TODO add your handling code here:
        Producciones abrir=new Producciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBotonProduccionActionPerformed

    private void jBotonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonVentasActionPerformed
        // TODO add your handling code here:
        Ventas abrir=new Ventas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBotonVentasActionPerformed

    private void jBotonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonClientesActionPerformed
        // TODO add your handling code here:
        Clientes abrir=new Clientes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBotonClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eleccion_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eleccion_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eleccion_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eleccion_NO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eleccion_NO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JButton jBotonClientes;
    private javax.swing.JButton jBotonProduccion;
    private javax.swing.JButton jBotonVentas;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
