/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Usos.ConexionBDR;
import Controlador.ControladorEmpleados;
import Modelo.Empleado;
import Usos.Leer;
import java.beans.XMLDecoder;
import java.beans.XMLEncoder;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Empleados extends javax.swing.JFrame {

    private ControladorEmpleados controladorEmpleados;
    private Object[][] matrizDatos;
    private String[] columnas = {"ID", "Nombre", "Puesto", "Salario", "Fecha Contratacion", "Estado"};
    private DefaultTableModel dtm;

    /**
     * Creates new form Empleados
     */
    public Empleados() {

        controladorEmpleados = new ControladorEmpleados();
        initComponents();
        this.setLocationRelativeTo(null);
        Leer.transparenciaBoton(jBotonAtras);

        // Inicializamos el modelo de tabla con las columnas vacías
        dtm = new DefaultTableModel(matrizDatos, columnas);
        visor.setModel(dtm);

        // Llenamos matrizDatos y actualizamos tabla
        actualizarMatrizDatos();

    }

    public void actualizarMatrizDatos() {

        ConexionBDR con = new ConexionBDR();
        Connection conexion = con.conectar();

        String sql = "SELECT * FROM empleados";
        List<Object[]> datos = new ArrayList<>();

        try (Statement st = conexion.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getInt("id");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("puesto");
                fila[3] = rs.getInt("salario");
                fila[4] = rs.getString("fecha_contratacion");
                fila[5] = rs.getString("estado");
                datos.add(fila);
            }

            // Pasamos de lista a matriz
            matrizDatos = new Object[datos.size()][columnas.length];
            for (int i = 0; i < datos.size(); i++) {
                matrizDatos[i] = datos.get(i);
            }

            // Actualizamos el modelo de la tabla
            dtm.setDataVector(matrizDatos, columnas);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar empleados: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBotonAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        jActualizar = new javax.swing.JButton();
        jAñadir = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextoNombre = new javax.swing.JTextField();
        jTextoSalario = new javax.swing.JTextField();
        jTextoPuesto = new javax.swing.JTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextoID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jfechacontratacion = new javax.swing.JTextField();
        jButtonEliminarVisualizacion = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        guardarDatos = new javax.swing.JButton();
        cargarDatos = new javax.swing.JButton();
        fondoprincipal = new javax.swing.JLabel();

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoGestiCor.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("GESTIÓN DE EMPLEADOS GESTICOR");
        jLabel3.setMaximumSize(new java.awt.Dimension(280, 20));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 450, 80));

        jLabel4.setFont(new java.awt.Font("Georgia Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("¡Le damos la Bienvenida Administrador/a!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 310, 20));

        jBotonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jBotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, -1));

        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Puesto", "Salario", "Fecha Contratacion", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        visor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(visor);
        if (visor.getColumnModel().getColumnCount() > 0) {
            visor.getColumnModel().getColumn(0).setResizable(false);
            visor.getColumnModel().getColumn(1).setResizable(false);
            visor.getColumnModel().getColumn(2).setResizable(false);
            visor.getColumnModel().getColumn(3).setResizable(false);
            visor.getColumnModel().getColumn(4).setResizable(false);
            visor.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 630, 440));

        jActualizar.setText("Refrescar Empleados");
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 190, -1));

        jAñadir.setText("Añadir");
        jAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(jAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 90, -1));

        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 80, -1));

        jLabel2.setText("Nombre:");

        jLabel5.setText("Puesto:");

        jLabel6.setText("Salario:");

        jLabel7.setText("Estado:");

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jTextoID.setEditable(false);

        jLabel8.setText("Contratacion: ");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEstado, 0, 155, Short.MAX_VALUE)
                            .addComponent(jTextoSalario)
                            .addComponent(jTextoNombre)
                            .addComponent(jTextoPuesto)
                            .addComponent(jTextoID, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfechacontratacion)))
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextoPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jfechacontratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 250));

        jButtonEliminarVisualizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jButtonEliminarVisualizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarVisualizacionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarVisualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 50, 40));

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 80, -1));

        guardarDatos.setText("Guardar datos en fichero xml");
        guardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(guardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 210, -1));

        cargarDatos.setText("Cargar datos de fichero xml");
        cargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(cargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 210, -1));

        fondoprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gradient_1920_1080.png"))); // NOI18N
        jPanel1.add(fondoprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAtrasActionPerformed
        // TODO add your handling code here:
        Eleccion abrir = new Eleccion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBotonAtrasActionPerformed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        // TODO add your handling code here:
        actualizarMatrizDatos();
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAñadirActionPerformed
        // TODO add your handling code here:

        // Obtener los valores de los campos de texto
        String nombre = jTextoNombre.getText();
        String puesto = jTextoPuesto.getText();
        String salarioStr = jTextoSalario.getText();
        String fechaContratacion = jfechacontratacion.getText();
        String estadoStr = (String) jComboBoxEstado.getSelectedItem();

        int salario = 0;
        try {
            salario = Integer.parseInt(salarioStr);  // Intentamos convertir el salario a int
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un salario válido");
            return;  // Salir del método si el salario es inválido
        }

        // Llamar al método del controlador pasando los datos obtenidos de los campos
        Empleado.Estado estado;
        estado = Empleado.Estado.valueOf(estadoStr.toUpperCase());  // Convertimos el String a Enum

        Empleado empleadoAñadir = new Empleado(WIDTH, nombre, puesto, salario, fechaContratacion, estado);

        controladorEmpleados.añadir(empleadoAñadir, estadoStr);

        // Refrescar la tabla de empleados
        actualizarMatrizDatos();
        jButtonEliminarVisualizacionActionPerformed(evt);
    }//GEN-LAST:event_jAñadirActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
        String idString = jTextoID.getText();
        String nombre = jTextoNombre.getText();
        String puesto = jTextoPuesto.getText();
        String salarioStr = jTextoSalario.getText();

        int salario = 0;
        try {
            salario = Integer.parseInt(salarioStr);  // Intentamos convertir el salario a int
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un salario válido");
            return;  // Salir del método si el salario es inválido
        }

        int id = 0;
        try {
            id = Integer.parseInt(idString);  // Intentamos convertir el id a int
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un id válido");
            return;  // Salir del método si el id es inválido
        }

        Empleado empleadoEliminar = new Empleado(id, nombre, puesto, salario);
        controladorEmpleados.eliminar(empleadoEliminar);
//        ControladorEmpleados.eliminar(idString,nombre,puesto,salario);
        actualizarMatrizDatos();
        jButtonEliminarVisualizacionActionPerformed(evt);
    }//GEN-LAST:event_jEliminarActionPerformed

    private void visorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visorMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = visor.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningun empleado.");
        } else {
            // Cogemos los valores que estan la fila seleccionada
            String idStr = visor.getValueAt(filaSeleccionada, 0).toString();
            String nombre = (String) visor.getValueAt(filaSeleccionada, 1);
            String puesto = (String) visor.getValueAt(filaSeleccionada, 2);
            int salario = Integer.parseInt(visor.getValueAt(filaSeleccionada, 3).toString());
            String fechaContratacion = (String) visor.getValueAt(filaSeleccionada, 4);
            String estado = (String) visor.getValueAt(filaSeleccionada, 5);

            // Se establecen los datos que han sido seleccionados previamente
            jTextoID.setText(String.valueOf(idStr));
            jTextoNombre.setText(nombre);
            jTextoPuesto.setText(puesto);
            jTextoSalario.setText(String.valueOf(salario));
            jfechacontratacion.setText(fechaContratacion);

            jComboBoxEstado.setSelectedItem(estado);
        }
    }//GEN-LAST:event_visorMouseClicked

    private void jButtonEliminarVisualizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarVisualizacionActionPerformed
        // TODO add your handling code here:
        jTextoID.setText("");
        jTextoNombre.setText("");
        jTextoPuesto.setText("");
        jTextoSalario.setText(String.valueOf(""));
        jfechacontratacion.setText("");
        jComboBoxEstado.setSelectedItem(-1);
    }//GEN-LAST:event_jButtonEliminarVisualizacionActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        // Obtener los valores de los campos de texto
        String idStr = jTextoID.getText();
        String nombre = jTextoNombre.getText();
        String puesto = jTextoPuesto.getText();
        String salarioStr = jTextoSalario.getText();
        String fechaContratacion = jfechacontratacion.getText();
        String estadoStr = (String) jComboBoxEstado.getSelectedItem();

        // Intentamos convertir el salario a int
        int salario = 0;
        try {
            salario = Integer.parseInt(salarioStr);  // Intentamos convertir el salario a int
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un salario válido");
            return;  // Salir del método si el salario es inválido
        }

        // Intentamos convertir el id a int
        int id = 0;
        try {
            id = Integer.parseInt(idStr);  // Intentamos convertir el id a int
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un id válido");
            return;  // Salir del método si el id es inválido
        }

        // Convertir el estado de String a Enum (ACTIVO o INACTIVO)
        Empleado.Estado estado = null;
        try {
            estado = Empleado.Estado.valueOf(estadoStr.toUpperCase());  // Convertimos el String a Enum
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Estado inválido.");
            return;  // Salir si el estado no es válido
        }

        // Crear un objeto Empleado con los datos obtenidos
        Empleado empleadomodificado = new Empleado(id, nombre, puesto, salario, fechaContratacion, estado);

        // Convertir el Enum a String para pasarlo a la base de datos
        String estadoDb = estado.name();

        // Llamar al método del controlador para editar el empleado
        controladorEmpleados.editar(empleadomodificado, estadoDb);

        // Refrescar la tabla de empleados
        actualizarMatrizDatos();


    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void cargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosActionPerformed
        // TODO add your handling code here:
        try {
        // Abrimos el archivo XML donde están guardados los empleados
        FileInputStream fis = new FileInputStream("listadoEmpleados.xml");
        XMLDecoder xmld = new XMLDecoder(new BufferedInputStream(fis));

        // Leemos la lista de empleados del archivo
        List<Empleado> listaEmpleados = (List<Empleado>) xmld.readObject();
        xmld.close();

        // Obtenemos el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) visor.getModel();
        model.setRowCount(0); // Limpiamos la tabla antes de cargar nuevos datos

        // Recorremos la lista y añadimos cada empleado como una fila en la tabla
         for (Empleado empleado : listaEmpleados) {
            // Llamamos al metodo añadir
            controladorEmpleados.añadir(empleado, empleado.getEstado().name());
            actualizarMatrizDatos();
        }
    } catch (Exception e) {
        System.err.println("\tERROR al leer el archivo listadoEmpleados.xml");
        e.printStackTrace();
    }
    }//GEN-LAST:event_cargarDatosActionPerformed

    private void guardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDatosActionPerformed
        try {
            // Se crea un flujo de salida para escribir en el archivo "listadoEmpleados.xml"
            FileOutputStream fos = new FileOutputStream("listadoEmpleados.xml");

            // Se crea un codificador XML que escribirá en el flujo de salida, con buffer para mayor eficiencia
            XMLEncoder xmle = new XMLEncoder(new BufferedOutputStream(fos));

            // Se crea una lista vacía donde se guardarán todos los empleados
            List<Empleado> listaEmpleados = new ArrayList<>();

            // Se obtiene el modelo de datos (las filas y columnas) de la tabla "visor"
            DefaultTableModel model = (DefaultTableModel) visor.getModel();
            int filas = model.getRowCount(); // Se obtiene el número de filas de la tabla

            // Se recorre cada fila de la tabla
            for (int i = 0; i < filas; i++) {
                // Se leen y convierten los datos de cada columna de la fila actual
                int id = Integer.parseInt(model.getValueAt(i, 0).toString());       // Columna 0: ID
                String nombre = model.getValueAt(i, 1).toString();                  // Columna 1: Nombre
                String puesto = model.getValueAt(i, 2).toString();                  // Columna 2: Puesto
                int salario = Integer.parseInt(model.getValueAt(i, 3).toString());  // Columna 3: Salario
                String fechaContratacion = model.getValueAt(i, 4).toString();       // Columna 4: Fecha de contratación

                // Asegurarse de que en la clase Empleado los enum, se vean igual que en la tabla
                Empleado.Estado estado = Empleado.Estado.valueOf(model.getValueAt(i, 5).toString()); // Columna 5: Estado (Activo/Inactivo)

                // Se crea un objeto Empleado con los datos leídos
                Empleado empleado = new Empleado(id, nombre, puesto, salario, fechaContratacion, estado);

                // Se añade el empleado a la lista
                listaEmpleados.add(empleado);
            }

            // Se escribe la lista completa de empleados en el archivo XML
            xmle.writeObject(listaEmpleados);

            // Se cierra el codificador para finalizar la escritura
            xmle.close();
        } catch (Exception e) {
            // En caso de error, se muestra un mensaje en consola
            System.err.println("\tERROR en la escritura de datos del archivo: listadoEmpleados.xml");
            e.printStackTrace(); // Opcional: muestra detalles técnicos del error
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarDatos;
    private javax.swing.JLabel fondoprincipal;
    private javax.swing.JButton guardarDatos;
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jAñadir;
    private javax.swing.JButton jBotonAtras;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminarVisualizacion;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JButton jEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextoID;
    private javax.swing.JTextField jTextoNombre;
    private javax.swing.JTextField jTextoPuesto;
    private javax.swing.JTextField jTextoSalario;
    private javax.swing.JTextField jfechacontratacion;
    public javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
