/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Usos.Leer;
import Controlador.ControladorVentas;
import Modelo.Venta;
import Usos.ConexionBDR;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.XMLEncoder;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Ventas_user extends javax.swing.JFrame {

    /**
     * Creates new form Empleados
     */
    public Ventas_user() {
        // Inicializar los componentes y aplicar transparencia al botón
        initComponents();
        RefrescarTabla("ventas");
        Leer.transparenciaBoton(jBotonAtras);
        this.setLocationRelativeTo(null);  // Centrar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBotonAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        Añadir = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        ExportarXML = new javax.swing.JButton();
        ExportarBIN = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        PrimerApartado = new javax.swing.JLabel();
        TextFieldNombre = new javax.swing.JTextField();
        SegundoApartado = new javax.swing.JLabel();
        TextFieldCantidad = new javax.swing.JTextField();
        TercerApartado = new javax.swing.JLabel();
        TextFieldPrecio = new javax.swing.JTextField();
        CuartoApartado = new javax.swing.JLabel();
        TextFieldVendedor = new javax.swing.JTextField();
        fondoprincipal = new javax.swing.JLabel();

        jLabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoGestiCor.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        jLabel3.setText("GESTIÓN DE VENTAS GESTICOR");
        jLabel3.setMaximumSize(new java.awt.Dimension(280, 20));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 450, 80));

        jBotonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jBotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(jBotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio", "Vendedor", "Fecha", "PrecioTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        visor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(visor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 490, 400));

        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });
        jPanel1.add(Añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel1.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        ExportarXML.setText("Exportar XML");
        ExportarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarXMLActionPerformed(evt);
            }
        });
        jPanel1.add(ExportarXML, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        ExportarBIN.setText("Exportar BIN");
        ExportarBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarBINActionPerformed(evt);
            }
        });
        jPanel1.add(ExportarBIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, -1, -1));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        PrimerApartado.setText("Nombre");
        jPanel1.add(PrimerApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        TextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 200, -1));

        SegundoApartado.setText("Cantidad");
        jPanel1.add(SegundoApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        TextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, -1));

        TercerApartado.setText("Precio");
        jPanel1.add(TercerApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel1.add(TextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 200, -1));

        CuartoApartado.setText("Vendedor");
        jPanel1.add(CuartoApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel1.add(TextFieldVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 200, -1));

        fondoprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gradient_800_600.png"))); // NOI18N
        jPanel1.add(fondoprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAtrasActionPerformed
        // TODO add your handling code here:
        Eleccion_user abrir = new Eleccion_user();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBotonAtrasActionPerformed

    private void visorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visorMouseClicked
        int filaSeleccionada = visor.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna venta.");
        } else {
            // Obtener el ID de la venta
            TextFieldNombre.setText(visor.getValueAt(filaSeleccionada, 1).toString());
            TextFieldCantidad.setText(visor.getValueAt(filaSeleccionada, 2).toString());
            TextFieldPrecio.setText(visor.getValueAt(filaSeleccionada, 3).toString());
            TextFieldVendedor.setText(visor.getValueAt(filaSeleccionada, 4).toString());
//            int fecha = (int) visor.getValueAt(filaSeleccionada, 5);
//            int precioTotal = (int) visor.getValueAt(filaSeleccionada, 6);
        }
    }//GEN-LAST:event_visorMouseClicked

    private void TextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreActionPerformed

    private void TextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCantidadActionPerformed

    private void ExportarBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarBINActionPerformed
        try {
            FileOutputStream fos = new FileOutputStream("ListadoVentas.bin");
            ObjectOutputStream oos = new ObjectOutputStream(fos);

            oos.writeObject(visor.getModel());  // Guarda el modelo de la tabla en binario
            oos.close();

            JOptionPane.showMessageDialog(this, "Datos exportados correctamente a binario.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar a binario: " + e.getMessage());
        }
    }//GEN-LAST:event_ExportarBINActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void ExportarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarXMLActionPerformed
        // TODO add your handling code here:
        FileOutputStream fos;
        XMLEncoder xmle;

        // necesitamos pasar el DefaultListModel a List para poder guardarlo como XML
        //List lista = (List) pasarModeloALista(listaPalabras);
        try {
            fos = new FileOutputStream("ListadoVentas.xml");
            xmle = new XMLEncoder(new BufferedOutputStream(fos));
            // guardar el TableModel

            // crear un ArrayList de Cliences
            // recorrer el TableModel, ir creando Clientes y añadiendolos a una colección
            xmle.writeObject(visor.getModel());
            xmle.close();
        } catch (Exception e) {
            System.err.println("\tERROR en la escritura de datos del archivo: " + "listadoColores.xml");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ExportarXMLActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        String nombre = TextFieldNombre.getText();
        String cantidad = TextFieldCantidad.getText();
        String precio = TextFieldPrecio.getText();
        String vendedor = TextFieldVendedor.getText();
        float Resultado = PrecioFinal(cantidad, precio);

        // Llamar al método del controlador pasando los datos obtenidos de los campos
        // ----- por hacer ---- 
        //ControladorVentas.añadir(0, nombre, 0, 0f, vendedor, 0, Resultado, 0);
        // Refrescar la tabla de empleados
        RefrescarTabla("ventas");
    }//GEN-LAST:event_AñadirActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        TextFieldNombre.setText("");
        TextFieldCantidad.setText("");
        TextFieldPrecio.setText("");
        TextFieldVendedor.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private float PrecioFinal(String cantidadStr, String precioStr) {
        float Resultado = 0;
        try {
            int cantidad = Integer.parseInt(cantidadStr);
            float precio = Float.parseFloat(precioStr);
            Resultado = cantidad * precio;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad y Precio deben ser números válidos.");
        }
        return Resultado;
    }

    public void RefrescarTabla(String tabla) {
        String sql = "select * from " + tabla;
        Statement st;
        ConexionBDR con = new ConexionBDR();
        Connection ConexionBDR = con.conectar();
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("IdVenta");
        model.addColumn("Nombre");
        model.addColumn("Cantidad");
        model.addColumn("Precio");
        model.addColumn("Vendedor");
        model.addColumn("FechaVenta");
        model.addColumn("PrecioFinal");
        model.addColumn("Iva");
        visor.setModel(model);

        String[] datos = new String[6];
        try {
            st = ConexionBDR.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                model.addRow(datos);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir;
    private javax.swing.JLabel CuartoApartado;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton ExportarBIN;
    private javax.swing.JButton ExportarXML;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel PrimerApartado;
    private javax.swing.JLabel SegundoApartado;
    private javax.swing.JLabel TercerApartado;
    private javax.swing.JTextField TextFieldCantidad;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldPrecio;
    private javax.swing.JTextField TextFieldVendedor;
    private javax.swing.JLabel fondoprincipal;
    private javax.swing.JButton jBotonAtras;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
